<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [14]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [6]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Ventas_por_Asesor.xlsx')
df.head(5)

,Ventas X Mes,12,7,8,13,6,21,17,17.1,23,...,37,10,Unnamed: 31,Unnamed: 32,178,Unnamed: 34,397,Unnamed: 36,236,Unnamed: 38
0,NaN,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2026-06-01 00:00:00,2026-07-01 00:00:00,NaN,NaN,2024,NaN,2025,NaN,2026,NaN
1,Nombre vendedor,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,811.0,Raking,Acum,Ranking,Acum,Ranking,Acum,Ranking
2,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4,NaN,88.0,NaN,22,NaN,45,2,21,NaN
3,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,3,2,88.0,NaN,11,NaN,51,NaN,26,NaN
4,MIGUEL ANGEL SONDEREGGER,,,,1,2,7,5,2,2,...,NaN,NaN,28.0,6,27,1,1,25,0,17

In [17]:
df.columns

Index([       'Unnamed: 0', 2024-02-01 00:00:00, 2024-03-01 00:00:00,
       2024-04-01 00:00:00, 2024-05-01 00:00:00, 2024-06-01 00:00:00,
       2024-07-01 00:00:00, 2024-08-01 00:00:00, 2024-09-01 00:00:00,
       2024-10-01 00:00:00, 2024-11-01 00:00:00, 2024-12-01 00:00:00,
       2025-01-01 00:00:00, 2025-02-01 00:00:00, 2025-03-01 00:00:00,
       2025-04-01 00:00:00, 2025-05-01 00:00:00, 2025-06-01 00:00:00,
       2025-07-01 00:00:00, 2025-08-01 00:00:00, 2025-09-01 00:00:00,
       2025-10-01 00:00:00, 2025-11-01 00:00:00, 2025-12-01 00:00:00,
       2026-01-01 00:00:00, 2026-02-01 00:00:00, 2026-03-01 00:00:00,
       2026-04-01 00:00:00, 2026-05-01 00:00:00, 2026-06-01 00:00:00,
       2026-07-01 00:00:00,       'Unnamed: 31',       'Unnamed: 32',
                      2024,       'Unnamed: 34',                2025,
             'Unnamed: 36',                2026,       'Unnamed: 38'],
      dtype='object')

In [ ]:
#Se revisó la base en excel, en excel se dividió la base en dos partes. De manera mensual y de manera anual. Se limpiarán ambos.

In [20]:

# Leer únicamente la pestaña de ventas_por_asesor_anual
df_anual = pd.read_excel("Ventas_por_Asesor.xlsx", sheet_name="ventas_por_asesor_anual")

In [21]:
df_anual.head(5)

,Nombre vendedor,Acum,Raking,Acum 2024,Ranking 2024,Acum 2025,Ranking 2025,Acum 2026,Ranking 2026
0,PEDRO GONZALEZ ESPINDOLA,88,NaN,22.0,NaN,45.0,2.0,21.0,NaN
1,VICTOR MANUEL SANCHEZ ARRO,88,NaN,11.0,NaN,51.0,NaN,26.0,NaN
2,MIGUEL ANGEL SONDEREGGER,28,6.0,27.0,1.0,1.0,25.0,0.0,17.0
3,JOSE ANTONIO LICONA MENDE,98,1.0,10.0,4.0,35.0,4.0,53.0,1.0
4,JAIME GONZALEZ CORONA,25,8.0,25.0,2.0,0.0,30.0,0.0,17.0

In [22]:
#Identificar valores nulos por columna
valores_nulos_anual=df_anual.isnull().sum()
valores_nulos_anual

Nombre vendedor    0
Acum               0
Raking             3
Acum 2024          1
Ranking 2024       3
Acum 2025          1
Ranking 2025       2
Acum 2026          1
Ranking 2026       3
dtype: int64

In [ ]:
#Se cambian los nulos por 0, ya que el 0 no modifica el resultado de la suma de ventas, y se puede considerar que no hubo ventas en ese año.
df_anual.fillna(0, inplace=True).head(5)

,Nombre vendedor,Acum,Raking,Acum 2024,Ranking 2024,Acum 2025,Ranking 2025,Acum 2026,Ranking 2026
0,PEDRO GONZALEZ ESPINDOLA,88,0.0,22.0,0.0,45.0,2.0,21.0,0.0
1,VICTOR MANUEL SANCHEZ ARRO,88,0.0,11.0,0.0,51.0,0.0,26.0,0.0
2,MIGUEL ANGEL SONDEREGGER,28,6.0,27.0,1.0,1.0,25.0,0.0,17.0
3,JOSE ANTONIO LICONA MENDE,98,1.0,10.0,4.0,35.0,4.0,53.0,1.0
4,JAIME GONZALEZ CORONA,25,8.0,25.0,2.0,0.0,30.0,0.0,17.0

In [26]:
#Corroborar que no hay valores nulos
valores_nulos_anual=df_anual.isnull().sum()
valores_nulos_anual

Nombre vendedor    0
Acum               0
Raking             0
Acum 2024          0
Ranking 2024       0
Acum 2025          0
Ranking 2025       0
Acum 2026          0
Ranking 2026       0
dtype: int64

In [ ]:
# Guardarla como un csv independiente
df_anual.to_csv("Ventas_A_Anual_Limpia.csv", index=False)

In [28]:
# Leer únicamente la pestaña de ventas_por_asesor_mensual
df_mensual = pd.read_excel("Ventas_por_Asesor.xlsx", sheet_name="ventas_por_asesor_mensual")

In [29]:
df_mensual.head(5)

,Vendedor,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00,2026-06-01 00:00:00,2026-07-01 00:00:00
0,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4.0,3.0,1.0,6.0,2.0,2.0,5.0,2.0,4.0,NaN
1,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,7.0,4.0,4.0,5.0,5.0,4.0,2.0,5.0,3.0,2.0
2,MIGUEL ANGEL SONDEREGGER,,,,1,2,7,5,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,JOSE ANTONIO LICONA MENDE,1,,,2,,,,3,2,...,4.0,3.0,4.0,11.0,4.0,12.0,10.0,6.0,9.0,1.0
4,JAIME GONZALEZ CORONA,,2,3,5,2,3,3,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
#Identificar valores nulos por columna
valores_nulos_mensual=df_mensual.isnull().sum()
valores_nulos_mensual

Vendedor                0
2024-02-01 00:00:00    21
2024-03-01 00:00:00    21
2024-04-01 00:00:00    21
2024-05-01 00:00:00    21
2024-06-01 00:00:00    21
2024-07-01 00:00:00    21
2024-08-01 00:00:00    21
2024-09-01 00:00:00    21
2024-10-01 00:00:00    21
2024-11-01 00:00:00    21
2024-12-01 00:00:00    21
2025-01-01 00:00:00    21
2025-02-01 00:00:00    21
2025-03-01 00:00:00    22
2025-04-01 00:00:00    19
2025-05-01 00:00:00    21
2025-06-01 00:00:00    38
2025-07-01 00:00:00    39
2025-08-01 00:00:00    40
2025-09-01 00:00:00    37
2025-10-01 00:00:00    37
2025-11-01 00:00:00    39
2025-12-01 00:00:00    38
2026-01-01 00:00:00    40
2026-02-01 00:00:00    37
2026-03-01 00:00:00    37
2026-04-01 00:00:00    37
2026-05-01 00:00:00    40
2026-06-01 00:00:00    38
2026-07-01 00:00:00    44
dtype: int64

In [31]:
#Se cambian los nulos por 0, ya que el 0 no modifica el resultado de la suma de ventas, y se puede considerar que no hubo ventas en ese mes.
df_mensual.fillna(0, inplace=True).head(5)

,Vendedor,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00,2026-06-01 00:00:00,2026-07-01 00:00:00
0,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4.0,3.0,1.0,6.0,2.0,2.0,5.0,2.0,4.0,0.0
1,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,7.0,4.0,4.0,5.0,5.0,4.0,2.0,5.0,3.0,2.0
2,MIGUEL ANGEL SONDEREGGER,,,,1,2,7,5,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,JOSE ANTONIO LICONA MENDE,1,,,2,,,,3,2,...,4.0,3.0,4.0,11.0,4.0,12.0,10.0,6.0,9.0,1.0
4,JAIME GONZALEZ CORONA,,2,3,5,2,3,3,3,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
#Corroborar que no hay valores nulos
valores_nulos_mensual=df_mensual.isnull().sum()
valores_nulos_mensual

Vendedor               0
2024-02-01 00:00:00    0
2024-03-01 00:00:00    0
2024-04-01 00:00:00    0
2024-05-01 00:00:00    0
2024-06-01 00:00:00    0
2024-07-01 00:00:00    0
2024-08-01 00:00:00    0
2024-09-01 00:00:00    0
2024-10-01 00:00:00    0
2024-11-01 00:00:00    0
2024-12-01 00:00:00    0
2025-01-01 00:00:00    0
2025-02-01 00:00:00    0
2025-03-01 00:00:00    0
2025-04-01 00:00:00    0
2025-05-01 00:00:00    0
2025-06-01 00:00:00    0
2025-07-01 00:00:00    0
2025-08-01 00:00:00    0
2025-09-01 00:00:00    0
2025-10-01 00:00:00    0
2025-11-01 00:00:00    0
2025-12-01 00:00:00    0
2026-01-01 00:00:00    0
2026-02-01 00:00:00    0
2026-03-01 00:00:00    0
2026-04-01 00:00:00    0
2026-05-01 00:00:00    0
2026-06-01 00:00:00    0
2026-07-01 00:00:00    0
dtype: int64

In [33]:
# Guardarla como un csv independiente
df_mensual.to_csv("Ventas_A_Mensual_Limpia.csv", index=False)