In [41]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [42]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Principales_Canales.xlsx')
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NaN,NaN,NaN,Datos erroneos no confiables de Sale-U,NaN,NaN,NaN,-,Sin datos,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ventas X Mes,Ventas Reportadas,12,7,8,13,6,21,17,17,...,38,30,41,41,35,37,NaN,NaN,NaN,NaN
3,Piso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Conversion,NaN,NaN
4,Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses

In [43]:
#Se observa que en el excel hay distintas tablas, por lo que se separarán en distintos dataframes, para poder trabajar con ellos de manera independiente. Se separan las tablas de Piso, Plaza y Digital. No se tomará la última tabla de digital debido a que no tiene información relevante para el análisis.

In [44]:
#Piso
#Data frame de la tabla de piso, se toma desde la fila 5 hasta la 14 y de la columna 0 a la 31, ya que es donde se encuentra la información relevante.
df_piso = df.iloc[4:14, 0:31].copy()
df_piso

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
4,Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Octubre, 25","Noviembre, 25","Diciembre, 25","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26"
5,Leads,329,19,76,87,55,92,77,57,43,...,72,81,76,97,94,105,79,115,85,36
6,Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72,81,76,97,94,105,79,115,84,36
7,SDC,-,-,-,-,-,51,32,28,38,...,24,21,27,27,18,24,18,24,22,7
8,PDM,22,13,35,40,28,35,31,28,14,...,48,43,22,46,28,41,36,45,42,16
9,Citas Programadas,9,28,15,38,78,75,65,37,31,...,72,81,76,97,94,105,12,73,28,11
10,Citas Efectivas,4,16,6,16,60,57,46,19,25,...,72,81,76,97,94,105,10,59,25,8
11,Ventas,9,4,10,1,3,10,9,6,3,...,11,9,9,6,7,8,9,9,11,2
12,Conversion,0.027356,0.210526,0.131579,0.011494,0.054545,0.108696,0.116883,0.105263,0.069767,...,0.152778,0.111111,0.118421,0.061856,0.074468,0.07619,0.113924,0.078261,0.129412,0.055556
13,Aporte,NaN,0.333333,1.428571,0.125,0.230769,1.666667,0.428571,0.352941,0.176471,...,0.289474,0.225,0.264706,0.176471,0.184211,0.266667,0.219512,0.219512,0.314286,0.054054

In [45]:
#Se pone como encabezado la primera fila del dataframe para un mejor análisis.
df_piso.columns = df_piso.iloc[0]
df_piso = df_piso.iloc[1:].reset_index(drop=True)

df_piso

4,Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Octubre, 25","Noviembre, 25","Diciembre, 25","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26"
0,Leads,329,19,76,87,55,92,77,57,43,...,72,81,76,97,94,105,79,115,85,36
1,Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72,81,76,97,94,105,79,115,84,36
2,SDC,-,-,-,-,-,51,32,28,38,...,24,21,27,27,18,24,18,24,22,7
3,PDM,22,13,35,40,28,35,31,28,14,...,48,43,22,46,28,41,36,45,42,16
4,Citas Programadas,9,28,15,38,78,75,65,37,31,...,72,81,76,97,94,105,12,73,28,11
5,Citas Efectivas,4,16,6,16,60,57,46,19,25,...,72,81,76,97,94,105,10,59,25,8
6,Ventas,9,4,10,1,3,10,9,6,3,...,11,9,9,6,7,8,9,9,11,2
7,Conversion,0.027356,0.210526,0.131579,0.011494,0.054545,0.108696,0.116883,0.105263,0.069767,...,0.152778,0.111111,0.118421,0.061856,0.074468,0.07619,0.113924,0.078261,0.129412,0.055556
8,Aporte,NaN,0.333333,1.428571,0.125,0.230769,1.666667,0.428571,0.352941,0.176471,...,0.289474,0.225,0.264706,0.176471,0.184211,0.266667,0.219512,0.219512,0.314286,0.054054

In [46]:
#Limpieza de datos, los valores nulos se reemplazan por NaN, ya que no se puede considerar que el valor fue 0 por que se interpretaría como que ocurrió y el resultado fue 0, en vez de que no hay registro de ello.
df_piso.fillna(np.nan, inplace=True)

4,Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Octubre, 25","Noviembre, 25","Diciembre, 25","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26"
0,Leads,329,19,76,87,55,92,77,57,43,...,72,81,76,97,94,105,79,115,85,36
1,Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72,81,76,97,94,105,79,115,84,36
2,SDC,-,-,-,-,-,51,32,28,38,...,24,21,27,27,18,24,18,24,22,7
3,PDM,22,13,35,40,28,35,31,28,14,...,48,43,22,46,28,41,36,45,42,16
4,Citas Programadas,9,28,15,38,78,75,65,37,31,...,72,81,76,97,94,105,12,73,28,11
5,Citas Efectivas,4,16,6,16,60,57,46,19,25,...,72,81,76,97,94,105,10,59,25,8
6,Ventas,9,4,10,1,3,10,9,6,3,...,11,9,9,6,7,8,9,9,11,2
7,Conversion,0.027356,0.210526,0.131579,0.011494,0.054545,0.108696,0.116883,0.105263,0.069767,...,0.152778,0.111111,0.118421,0.061856,0.074468,0.07619,0.113924,0.078261,0.129412,0.055556
8,Aporte,NaN,0.333333,1.428571,0.125,0.230769,1.666667,0.428571,0.352941,0.176471,...,0.289474,0.225,0.264706,0.176471,0.184211,0.266667,0.219512,0.219512,0.314286,0.054054

In [47]:
#Identificar valores nulos por columna
valores_nulos=df_piso.isnull().sum()
valores_nulos

4
Piso              0
Febrero, 24       2
Marzo, 24         1
Abril, 24         1
Mayo, 24          1
Junio, 24         1
Julio, 24         1
Agosto, 24        1
Septiembre, 24    1
Octubre, 24       1
Noviembre, 24     1
Diciembre, 24     1
Enero, 25         0
Febrero, 25       0
Marzo, 25         0
Abril, 25         0
Mayo, 25          0
Junio, 25         0
Julio, 25         0
Agosto, 25        0
Septiembre, 25    0
Octubre, 25       0
Noviembre, 25     0
Diciembre, 25     0
Enero, 26         0
Febrero, 26       0
Marzo, 26         0
Abril, 26         0
Mayo, 26          0
Junio, 26         0
Julio,26          0
dtype: int64

In [48]:
#Plaza
#Data frame de la tabla de plaza, se toma desde la fila 18 hasta la 29 y de la columna 0 a la 31, ya que es donde se encuentra la información relevante. Y se hace una copia del mismo para no modificar el original.
df_plaza = df.iloc[17:29, 0:31].copy()
df_plaza

df_plaza.columns = df_plaza.iloc[0]
df_plaza = df_plaza.iloc[1:].reset_index(drop=True)

df_plaza

17,Plazas,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Octubre, 25","Noviembre, 25","Diciembre, 25","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26"
0,Leads,0,0,25,28,68,294,248,52,59,...,324,274,325,290,433,401,351,352,403,145
1,Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,226,209,291,261,387,364,351,347,403,145
2,SDC,-,-,-,-,-,-,-,-,-,...,38,31,34,23,25,26,12,18,16,3
3,PDM,-,-,1,11,5,6,17,8,5,...,43,33,18,15,39,35,30,31,41,12
4,Citas Programadas,NaN,NaN,1,3,2,30,50,13,13,...,77,60,46,23,105,70,41,68,100,26
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.141538,0.07931,0.242494,0.174564,0.116809,0.193182,0.248139,0.17931
6,Citas Efectivas,NaN,NaN,NaN,2,2,8,18,4,6,...,48,32,41,19,82,55,31,49,59,15
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.065517,0.189376,0.137157,0.088319,0.139205,0.146402,NaN
8,Ventas,0,0,0,0,0,2,3,0,2,...,12,11,9,6,6,7,7,7,10,1
9,Conversion,0,0,0,0,0,0.006803,0.012097,0,0.033898,...,0.037037,0.040146,0.027692,0.02069,0.013857,0.017456,0.019943,0.019886,0.024814,0.006897
10,Aporte,NaN,0,0,0,0,0.333333,0.142857,0,0.117647,...,0.315789,0.275,0.264706,0.176471,0.157895,0.233333,0.170732,0.170732,0.285714,0.027027

In [49]:
#Identificar valores nulos por columna
valores_nulos=df_plaza.isnull().sum()
valores_nulos

17
Plazas            2
Febrero, 24       6
Marzo, 24         5
Abril, 24         4
Mayo, 24          3
Junio, 24         3
Julio, 24         3
Agosto, 24        3
Septiembre, 24    3
Octubre, 24       3
Noviembre, 24     3
Diciembre, 24     3
Enero, 25         3
Febrero, 25       3
Marzo, 25         3
Abril, 25         3
Mayo, 25          3
Junio, 25         3
Julio, 25         3
Agosto, 25        2
Septiembre, 25    2
Octubre, 25       2
Noviembre, 25     2
Diciembre, 25     1
Enero, 26         0
Febrero, 26       0
Marzo, 26         0
Abril, 26         0
Mayo, 26          0
Junio, 26         0
Julio,26          1
dtype: int64

In [58]:
#Limpieza de datos, los valores nulos se reemplazan por NaN, ya que no se puede considerar que el valor fue 0 por que se interpretaría como que ocurrió y el resultado fue 0, en vez de que no hay registro de ello.
df_plaza.fillna(np.nan, inplace=True)

17,Plazas,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Octubre, 25","Noviembre, 25","Diciembre, 25","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26"
0,Leads,0,0,25,28,68,294,248,52,59,...,324,274,325,290,433,401,351,352,403,145
1,Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,226,209,291,261,387,364,351,347,403,145
2,SDC,-,-,-,-,-,-,-,-,-,...,38,31,34,23,25,26,12,18,16,3
3,PDM,-,-,1,11,5,6,17,8,5,...,43,33,18,15,39,35,30,31,41,12
4,Citas Programadas,NaN,NaN,1,3,2,30,50,13,13,...,77,60,46,23,105,70,41,68,100,26
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.141538,0.07931,0.242494,0.174564,0.116809,0.193182,0.248139,0.17931
6,Citas Efectivas,NaN,NaN,NaN,2,2,8,18,4,6,...,48,32,41,19,82,55,31,49,59,15
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.065517,0.189376,0.137157,0.088319,0.139205,0.146402,NaN
8,Ventas,0,0,0,0,0,2,3,0,2,...,12,11,9,6,6,7,7,7,10,1
9,Conversion,0,0,0,0,0,0.006803,0.012097,0,0.033898,...,0.037037,0.040146,0.027692,0.02069,0.013857,0.017456,0.019943,0.019886,0.024814,0.006897
10,Aporte,NaN,0,0,0,0,0.333333,0.142857,0,0.117647,...,0.315789,0.275,0.264706,0.176471,0.157895,0.233333,0.170732,0.170732,0.285714,0.027027

In [ ]:
#Corroborar que los valores nulos fueron reemplazados por NaN
valores_nulos=df_plaza.isnull().sum()
valores_nulos

17
Plazas            0
Febrero, 24       0
Marzo, 24         0
Abril, 24         0
Mayo, 24          0
Junio, 24         0
Julio, 24         0
Agosto, 24        0
Septiembre, 24    0
Octubre, 24       0
Noviembre, 24     0
Diciembre, 24     0
Enero, 25         0
Febrero, 25       0
Marzo, 25         0
Abril, 25         0
Mayo, 25          0
Junio, 25         0
Julio, 25         0
Agosto, 25        0
Septiembre, 25    0
Octubre, 25       0
Noviembre, 25     0
Diciembre, 25     0
Enero, 26         0
Febrero, 26       0
Marzo, 26         0
Abril, 26         0
Mayo, 26          0
Junio, 26         0
Julio,26          0
dtype: int64

In [52]:
#Digital
df_digital = df.iloc[32:42, 0:31].copy()
df_digital

df_digital.columns = df_digital.iloc[0]
df_digital = df_digital.iloc[1:].reset_index(drop=True)

df_digital

32,Digital,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Octubre, 25","Noviembre, 25","Diciembre, 25","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26"
0,Leads,57,145,129,463,350,192,1112,1353,1142,...,688,554,908,922,635,980,834,667,748,298
1,Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,329,342,594,674,457,618,179,170,200,64
2,SDC,-,-,-,-,-,-,-,-,-,...,50,42,39,23,21,16,32,30,28,3
3,PDM,-,-,-,-,-,-,-,8,7,...,32,22,23,22,22,25,35,35,28,12
4,Citas Programadas,3,6,23,43,43,36,57,107,83,...,110,97,90,110,85,78,83,140,101,26
5,Citas Efectivas,2,5,5,23,19,14,18,27,33,...,60,55,51,56,43,36,59,103,53,15
6,Ventas,NaN,1,NaN,NaN,1,2,NaN,6,1,...,10,14,8,6,13,11,8,9,7,1
7,Conversion,0,0.006897,0,0,0.002857,0.010417,0,0.004435,0.000876,...,0.014535,0.025271,0.008811,0.006508,0.020472,0.011224,0.009592,0.013493,0.009358,0.003356
8,Aporte,NaN,0.083333,0,0,0.076923,0.333333,0,0.352941,0.058824,...,0.263158,0.35,0.235294,0.176471,0.342105,0.366667,0.195122,0.219512,0.2,0.027027

In [63]:
#Identificar valores nulos por columna
valores_nulos=df_digital.isnull().sum()
valores_nulos

32
Digital           0
Febrero, 24       3
Marzo, 24         1
Abril, 24         2
Mayo, 24          2
Junio, 24         1
Julio, 24         1
Agosto, 24        2
Septiembre, 24    1
Octubre, 24       1
Noviembre, 24     1
Diciembre, 24     1
Enero, 25         1
Febrero, 25       1
Marzo, 25         1
Abril, 25         1
Mayo, 25          1
Junio, 25         1
Julio, 25         1
Agosto, 25        0
Septiembre, 25    0
Octubre, 25       0
Noviembre, 25     0
Diciembre, 25     0
Enero, 26         0
Febrero, 26       0
Marzo, 26         0
Abril, 26         0
Mayo, 26          0
Junio, 26         0
Julio,26          0
dtype: int64

In [79]:
#Limpieza de datos, los valores nulos se reemplazan por NaN, ya que no se puede considerar que el valor fue 0 por que se interpretaría como que ocurrió y el resultado fue 0, en vez de que no hay registro de ello.
df_digital.fillna('NaN', inplace=True)

32,Digital,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Octubre, 25","Noviembre, 25","Diciembre, 25","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26"
0,Leads,57,145,129,463,350,192,1112,1353,1142,...,688,554,908,922,635,980,834,667,748,298
1,Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,329,342,594,674,457,618,179,170,200,64
2,SDC,-,-,-,-,-,-,-,-,-,...,50,42,39,23,21,16,32,30,28,3
3,PDM,-,-,-,-,-,-,-,8,7,...,32,22,23,22,22,25,35,35,28,12
4,Citas Programadas,3,6,23,43,43,36,57,107,83,...,110,97,90,110,85,78,83,140,101,26
5,Citas Efectivas,2,5,5,23,19,14,18,27,33,...,60,55,51,56,43,36,59,103,53,15
6,Ventas,NaN,1,NaN,NaN,1,2,NaN,6,1,...,10,14,8,6,13,11,8,9,7,1
7,Conversion,0,0.006897,0,0,0.002857,0.010417,0,0.004435,0.000876,...,0.014535,0.025271,0.008811,0.006508,0.020472,0.011224,0.009592,0.013493,0.009358,0.003356
8,Aporte,NaN,0.083333,0,0,0.076923,0.333333,0,0.352941,0.058824,...,0.263158,0.35,0.235294,0.176471,0.342105,0.366667,0.195122,0.219512,0.2,0.027027

In [80]:
#Corroborar que los valores nulos fueron reemplazados por NaN
valores_nulos=df_digital.isnull().sum()
valores_nulos

32
Digital           0
Febrero, 24       0
Marzo, 24         0
Abril, 24         0
Mayo, 24          0
Junio, 24         0
Julio, 24         0
Agosto, 24        0
Septiembre, 24    0
Octubre, 24       0
Noviembre, 24     0
Diciembre, 24     0
Enero, 25         0
Febrero, 25       0
Marzo, 25         0
Abril, 25         0
Mayo, 25          0
Junio, 25         0
Julio, 25         0
Agosto, 25        0
Septiembre, 25    0
Octubre, 25       0
Noviembre, 25     0
Diciembre, 25     0
Enero, 26         0
Febrero, 26       0
Marzo, 26         0
Abril, 26         0
Mayo, 26          0
Junio, 26         0
Julio,26          0
dtype: int64

In [82]:
import numpy as np

for dataframe in [df_piso, df_plaza, df_digital]:
    dataframe.replace("-", np.nan, inplace=True)

In [83]:
#Exportar los dataframes en un documento limpios a archivos .csv para su posterior análisis
df_piso.to_csv("Ventas_Piso_Mensual_Limpia.csv", index=False)
df_plaza.to_csv("Ventas_Plaza_Mensual_Limpia.csv", index=False)
df_digital.to_csv("Ventas_Digital_Mensual_Limpia.csv", index=False)